### ISSUE TITLE
[Feature] Add TempCleaner.bat 

### ISSUE THREAD

**Issue by akisblack** [Odyssey346/Fixdows#4]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add tempcleaner.bat (from Winblows Maintenance Tool) as a new thing

**Describe alternatives you've considered**
Do it manually

**Additional context**
i cant understand c sharp go do it yourself :)

[tempcleaner.zip](https://github.com/Odyssey346/Fixdows/files/6333604/tempcleaner.zip)

**Comment by Odyssey346** [comment]
I believe that Disk Cleanup can do that, but, sometimes it doesn't do the job properly. Priority-2.

**Comment by akisblack** [comment]
> 
> 
> I believe that Disk Cleanup can do that, but, sometimes it doesn't do the job properly. Priority: 2.

Disk Cleanup doesn't wipe the whole folder.

**Comment by Odyssey346** [comment]
I said that it doesn't do the job properly. I will add this, but at the moment, I think I have more important things to focus on, so I am going to set this to Priority level 2.

**Comment by Odyssey346** [comment]
Feel free to try to convince me.

**Comment by akisblack** [comment]
windows is bloat and doesnt remove the temp files at shutdown. go fix it, i will get devnol to use it on his windows partition

**Comment by Odyssey346** [comment]
> windows is bloat

I already knew that.
> Doesn't remove the temp files at shutdown

Windows already takes long enough to shut down. Do you want it to use even more time? Although, I guess it could partially delete temporary files, but I'm not a Microsoft developer, so I can't do anything about that.

> Go fix it, I will get Devnol to use it on his Windows partition

He doesn't use Windows.

**Comment by Odyssey346** [comment]
Done
