### ISSUE TITLE
Make a logo for Fixdows

### ISSUE THREAD

**Issue by Odyssey346** [Odyssey346/Fixdows#5]
We should really get a logo for it, because it currently uses a generic Windows executable icon, and this is not preferred. Unfortunately, I'm not able to make one as I don't know what thing would remind me of Fixdows.

**Comment by Rexogamer** [comment]
I am working on this

**Comment by Odyssey346** [comment]
@Rexogamer are you still working on the logo, or am I safe to unassign you?

**Comment by Rexogamer** [comment]
My apologies for the wait - I am still prepairing this, will keep you posted

**Comment by Odyssey346** [comment]
It's fine, no pressure

**Comment by Odyssey346** [comment]
@Rexogamer You have been unassigned. If you would like to be re-assigned, tell me an excuse and I will re-assign you. Reason: have no way of contacting him anymore.

**Comment by Rexogamer** [comment]
have you decided on the font yet?

**Comment by Odyssey346** [comment]
I have. Muli.

**Comment by Odyssey346** [comment]
I will get right to work designing a banner.

**Comment by Odyssey346** [comment]
This time I should be actually motivated :D

**Comment by Odyssey346** [comment]
The font is actually called Mulish, which they apparently changed the name just because Muli is offensive to some communities(?). Looks better IMO, there's probably not a difference though.

Source: [Reddit](https://www.reddit.com/r/fonts/comments/i1b44r/did_google_remove_muli_font_from_its_collection/fzw7cd1?utm_source=share&utm_medium=web2x&context=3)

**Comment by Odyssey346** [comment]
New banner! This time, your eyes don't burn.
![newbanner](https://user-images.githubusercontent.com/57069715/116723129-71fae000-a9df-11eb-9d3e-fcb8cbfb80ca.png)

**Comment by jameskorah** [comment]
Hi @Odyssey346,

What do you think of this?
![image](https://user-images.githubusercontent.com/83485518/116824196-cc11b780-ab3d-11eb-849f-6ebee9474c99.png)

**Comment by Odyssey346** [comment]
that's pretty good! can you make it standalone as well?

**Comment by Odyssey346** [comment]
Done by @jameskorah.
